CREATE TABLE Usuario (
    ID INT PRIMARY KEY NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

CREATE TABLE Imagens (
    ID INT PRIMARY KEY NOT NULL,
    Link VARCHAR(255) NOT NULL
);

CREATE TABLE Texto (
    ID INT PRIMARY KEY NOT NULL,
    Texto VARCHAR(255) NOT NULL
);

CREATE TABLE Emocoes (
    ID INT PRIMARY KEY NOT NULL,
    Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Extracoes (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDUsuario INT NOT NULL,
    IDImagem INT NOT NULL,
    IDTexto_imagem INT NOT NULL,
    IDEmocao INT NOT NULL,
    Nota_texto INT NOT NULL,
    Nota_emocao INT NOT NULL,
    FOREIGN KEY (IDImagem) REFERENCES Imagens(ID),
    FOREIGN KEY (IDEmocao) REFERENCES Emocoes(ID),
    FOREIGN KEY (IDTexto_imagem) REFERENCES Texto(ID),
    FOREIGN KEY (IDUsuario) REFERENCES Usuario(ID)
);